In [1]:
import numpy as np
from numpy.ma.core import shape

np_array = np.array([23, 43, 56, 67, 12, 98, 37])
print(np_array)
print(type(np_array))
print(np_array.shape)
print(np_array.size)
print(np_array.dtype)

[23 43 56 67 12 98 37]
<class 'numpy.ndarray'>
(7,)
7
int64


In [2]:
zeros_np_array = np.zeros(
    shape= (5, 3),
    dtype= 'int'
)
print(zeros_np_array)
print(zeros_np_array.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
int64


In [3]:
ones_np_array = np.ones(
    shape=(3, 4),
    dtype= "int"
)
print(ones_np_array)
print(ones_np_array.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int64


In [4]:
identity_array = np.eye(5)
print(identity_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
np_array_specific_num = np.full(
    fill_value= 23,
    shape= (4, 3)
)
print(np_array_specific_num)

[[23 23 23]
 [23 23 23]
 [23 23 23]
 [23 23 23]]


In [6]:
np_array_random_num = np.arange(
    start= 20, stop= 50, step= 3
)
print(np_array_random_num)

[20 23 26 29 32 35 38 41 44 47]


In [11]:
my_2d_array = np.array(
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12],
     [13, 14, 15, 16]]
)
print(my_2d_array)
print(my_2d_array[2, 2])
print(my_2d_array[3, -1])
print(my_2d_array[2, -3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
11
16
10


In [12]:
my_2d_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [17]:
print(my_2d_array[1:3, 1:3])
print(my_2d_array[0:4:2, 1:4:2])
print(my_2d_array[1:4:2, 0:3:2])

[[ 6  7]
 [10 11]]
[[ 2  4]
 [10 12]]
[[ 5  7]
 [13 15]]


Numpy Array Iteration

In [18]:
print(np_array)

[23 43 56 67 12 98 37]


In [19]:
"""Iterate by value"""
for val in np_array:
    print(val)

23
43
56
67
12
98
37


In [20]:
"""Iterate by index"""
for i in range(len(np_array)):
    print(np_array[i])

23
43
56
67
12
98
37


In [21]:
"""Iterate by value and Index"""
for i, val in enumerate(np_array):
    print(f"Index: {i} Value: {val}")

Index: 0 Value: 23
Index: 1 Value: 43
Index: 2 Value: 56
Index: 3 Value: 67
Index: 4 Value: 12
Index: 5 Value: 98
Index: 6 Value: 37


In [23]:
New_array = np.arange(
    start= 40, stop= 120, step= 7,
)
print(New_array)
for index, value in enumerate(New_array):
    print(f"Index: {index}, Value: {value}")

[ 40  47  54  61  68  75  82  89  96 103 110 117]
Index: 0, Value: 40
Index: 1, Value: 47
Index: 2, Value: 54
Index: 3, Value: 61
Index: 4, Value: 68
Index: 5, Value: 75
Index: 6, Value: 82
Index: 7, Value: 89
Index: 8, Value: 96
Index: 9, Value: 103
Index: 10, Value: 110
Index: 11, Value: 117


In [24]:
""" Reshaping"""
one_array = np.ones(shape = (3, 3, 2))
print(one_array)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [25]:
one_array_reshaped = one_array.reshape(1, 6, 3)
print(one_array_reshaped)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [28]:
Array_specific_value = np.full(
    shape= (2, 3, 3, 2),
    fill_value= 9
)
print(Array_specific_value.ndim)
print(Array_specific_value.shape)
print(Array_specific_value)

4
(2, 3, 3, 2)
[[[[9 9]
   [9 9]
   [9 9]]

  [[9 9]
   [9 9]
   [9 9]]

  [[9 9]
   [9 9]
   [9 9]]]


 [[[9 9]
   [9 9]
   [9 9]]

  [[9 9]
   [9 9]
   [9 9]]

  [[9 9]
   [9 9]
   [9 9]]]]


In [30]:
Array_specific_value_reshaped = Array_specific_value.reshape(3, 3, -1)
print(Array_specific_value_reshaped)
print(Array_specific_value_reshaped.shape)
print(Array_specific_value_reshaped.ndim)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]
(3, 3, 4)
3


In [32]:
random_array = np.array([8, 3, 15, 59, 38, 5, 23, 11, 30])
sorted_random_array = np.sort(random_array)
reversed_sorted_random_array = np.sort(random_array)[::-1]
print(sorted_random_array)
print(reversed_sorted_random_array)

[ 3  5  8 11 15 23 30 38 59]
[59 38 30 23 15 11  8  5  3]


In [34]:
print(np.argmax(random_array))
print(np.argmin(random_array))

3
1


In [37]:
New_array2 = np.arange(start= 20, stop = 50)
print(New_array2)
splited_New_array2 = np.split(New_array2,
                              indices_or_sections= 3)
print(splited_New_array2)
print(splited_New_array2[0])
print(splited_New_array2[2])

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]
[array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]), array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39]), array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])]
[20 21 22 23 24 25 26 27 28 29]
[40 41 42 43 44 45 46 47 48 49]


In [38]:
"""Dot Product"""
dot_product = np.dot(splited_New_array2[0], splited_New_array2[1])
print(dot_product)

8535


In [39]:
"""Matrix Transpose"""
Matrix_transpose = np.full(
    shape= (3, 4),
    fill_value= 7
)
print(Matrix_transpose)
print(Matrix_transpose.T)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]


In [40]:
print(New_array2)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]


In [43]:
"""filtering with condition"""
filter_mask = New_array2 % 2 == 0
print(filter_mask)
filtered_New_array2 = New_array2[filter_mask]
print(filtered_New_array2)

[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True False  True False
  True False  True False  True False]
[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [44]:
array_for_filtering = np.arange(start= 20, stop = 150, step= 3)
print(array_for_filtering)

[ 20  23  26  29  32  35  38  41  44  47  50  53  56  59  62  65  68  71
  74  77  80  83  86  89  92  95  98 101 104 107 110 113 116 119 122 125
 128 131 134 137 140 143 146 149]


In [49]:
"""Custom Filtering Method"""
def my_filter_method(x):
    # logic
    if x % 2 == 1:
        return True
    else:
        return False

filtered_iterable = filter(my_filter_method, array_for_filtering)
filtered_array = np.array(
    list(filtered_iterable))
print(filtered_array)

[ 23  29  35  41  47  53  59  65  71  77  83  89  95 101 107 113 119 125
 131 137 143 149]


In [50]:
New_array2 = New_array2 + 5
print(New_array2)

[25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54]


In [53]:
one_d_array = np.array([5, 6])
print(one_d_array)
two_d_array = np.array(
    [[3, 9],
     [8,4],
     [2,7],
     [5, 9]]
)
print(two_d_array)
print(one_d_array * two_d_array)

[5 6]
[[3 9]
 [8 4]
 [2 7]
 [5 9]]
[[15 54]
 [40 24]
 [10 42]
 [25 54]]
